# Generated by Django 5.2.17 on 2026-08-08 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_id', models.CharField(max_length=64, unique=True)),
                ('lichess_username', models.CharField(max_length=64)),
                ('encrypted_access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lichess_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
