# Generated by Django 5.2.17 on 2026-08-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineLineCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=100, unique=True)),
                ('depth', models.PositiveSmallIntegerField()),
                ('score_type', models.CharField(choices=[('cp', 'Centipawns'), ('mate', 'Mate')], max_length=8)),
                ('score_value', models.IntegerField()),
                ('best_move_uci', models.CharField(blank=True, max_length=8, null=True)),
                ('pv_uci', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lichess', 'Lichess')], default='lichess', max_length=16)),
                ('fen', models.CharField(max_length=100)),
                ('params_key', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'fen', 'params_key'], name='explorer_ca_source_528b31_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'fen', 'params_key'), name='unique_position_stats_cache_key')],
            },
        ),
    ]
