# Generated by Django 5.2.17 on 2026-08-08 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RepertoireMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_fen', models.CharField(max_length=100)),
                ('san', models.CharField(max_length=16)),
                ('uci', models.CharField(max_length=8)),
                ('resulting_fen', models.CharField(max_length=100)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='repertoire.repertoire')),
            ],
            options={
                'indexes': [models.Index(fields=['repertoire', 'origin_fen'], name='repertoire__reperto_a37876_idx')],
                'constraints': [models.UniqueConstraint(fields=('repertoire', 'origin_fen', 'uci'), name='unique_repertoire_edge')],
            },
        ),
    ]
