# Generated by Django 5.2.17 on 2026-08-10 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_profiles_and_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningTemplateRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('changelog', models.TextField(blank=True)),
                ('tree', models.JSONField(default=dict)),
                ('lines', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='repertoire.openingtemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='repertoire',
            name='source_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='repertoire.openingtemplaterelease'),
        ),
        migrations.CreateModel(
            name='ProfileTemplateRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='repertoire.repertoireprofile')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_links', to='repertoire.openingtemplaterelease')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='openingtemplaterelease',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
        migrations.AddConstraint(
            model_name='profiletemplaterelease',
            constraint=models.UniqueConstraint(fields=('profile', 'release'), name='unique_release_per_profile'),
        ),
    ]
