# Generated by Django 5.2.17 on 2026-08-12 08:52

from django.db import migrations, models


def backfill_release_summaries(apps, schema_editor):
    release_model = apps.get_model("repertoire", "OpeningTemplateRelease")
    for release in release_model.objects.all().iterator():
        lines = release.lines or []
        step_lines = [line.get("steps", []) for line in lines]
        common = []
        for steps in zip(*step_lines, strict=False):
            first = steps[0]
            if any(step.get("uci") != first.get("uci") for step in steps[1:]):
                break
            common.append(str(first.get("san", "")))
        tokens = []
        for ply, san in enumerate(common):
            if ply % 2 == 0:
                tokens.extend([f"{ply // 2 + 1}.", san])
            else:
                tokens.append(san)
        release.common_start = " ".join(tokens)
        release.line_count = len(lines)
        release.save(update_fields=["common_start", "line_count"])


class Migration(migrations.Migration):
    dependencies = [
        ("repertoire", "0005_openingtemplate_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="openingtemplaterelease",
            name="common_start",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="openingtemplaterelease",
            name="line_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_release_summaries, migrations.RunPython.noop),
    ]
