# Generated by Django 5.2.17 on 2026-08-08 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire_id', models.BigIntegerField()),
                ('is_retry_pass', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DrillLineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('perfect', 'Perfect'), ('failed', 'Failed')], max_length=8)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_results', to='drills.drillsession')),
            ],
        ),
        migrations.CreateModel(
            name='DrillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_fen', models.CharField(max_length=100)),
                ('played_uci', models.CharField(max_length=8)),
                ('is_correct', models.BooleanField()),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('cp_loss', models.IntegerField(blank=True, null=True)),
                ('is_bad', models.BooleanField(blank=True, null=True)),
                ('line_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='drills.drillsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drillsession',
            index=models.Index(fields=['user', 'repertoire_id'], name='drills_dril_user_id_50d80b_idx'),
        ),
        migrations.AddConstraint(
            model_name='drilllineresult',
            constraint=models.UniqueConstraint(fields=('session', 'line_id'), name='unique_drill_line_result_per_session'),
        ),
        migrations.AddIndex(
            model_name='drillattempt',
            index=models.Index(fields=['session', 'origin_fen'], name='drills_dril_session_f1f054_idx'),
        ),
    ]
