# Generated by Django 5.2.17 on 2026-08-10 04:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_sources(apps, schema_editor):
    Session = apps.get_model("drills", "DrillSession")
    Source = apps.get_model("drills", "DrillSessionRepertoire")
    Source.objects.bulk_create(
        Source(session_id=session.id, repertoire_id=session.repertoire_id)
        for session in Session.objects.all().iterator()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
        ('repertoire', '0003_openingtemplate_openingtemplaterelease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillsession',
            name='prefix_uci',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drillsession',
            name='selected_fen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drillsession',
            name='selected_ply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillsession',
            name='start_mode',
            field=models.CharField(choices=[('beginning', 'Beginning'), ('selected_position', 'Selected position')], default='beginning', max_length=20),
        ),
        migrations.CreateModel(
            name='DrillSessionRepertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_source_links', to='repertoire.repertoire')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoire_sources', to='drills.drillsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'repertoire'), name='unique_session_repertoire_source')],
            },
        ),
        migrations.CreateModel(
            name='DrillSessionTemplateRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drill_source_links', to='repertoire.openingtemplaterelease')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sources', to='drills.drillsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'release'), name='unique_session_template_source')],
            },
        ),
        migrations.RunPython(backfill_sources, migrations.RunPython.noop),
    ]
