# Generated by Django 5.2.17 on 2026-08-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_drillsession_prefix_uci_drillsession_selected_fen_and_more'),
        ('repertoire', '0003_openingtemplate_openingtemplaterelease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillsession',
            name='repertoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_sessions', to='repertoire.repertoire'),
        ),
    ]
